DROP TABLE IF EXISTS CONCERT;
DROP TABLE IF EXISTS PERFORMER;
CREATE TABLE CONCERT(
ID              LONG PRIMARY KEY AUTO_INCREMENT,
TITLE           VARCHAR(255),
DATE            TIMESTAMP,
PERFORMER_ID    LONG);

CREATE TABLE PERFORMER(
ID       LONG PRIMARY KEY AUTO_INCREMENT,
NAME     VARCHAR(255),
IMAGEURI VARCHAR(255),
GENRE    VARCHAR(30));

ALTER TABLE CONCERT ADD FOREIGN KEY (PERFORMER_ID) REFERENCES PERFORMER(ID);

INSERT INTO PERFORMER (ID, NAME, IMAGEURI, GENRE) VALUES(1,'Panic! at the Disco','PanicAtTheDisco.jpg','Pop');
INSERT INTO PERFORMER (ID, NAME, IMAGEURI, GENRE) VALUES(2,'Ed Sheeran','EdSheeran.jpg','Pop');
INSERT INTO PERFORMER (ID, NAME, IMAGEURI, GENRE) VALUES(3,'Kendrick Lamar','KendrickLamar.jpg','HipHop');
INSERT INTO PERFORMER (ID, NAME, IMAGEURI, GENRE) VALUES(4,'Bruno Mars','BrunoMars.jpg','RhythmAndBlues');
INSERT INTO PERFORMER (ID, NAME, IMAGEURI, GENRE) VALUES(5,'Twenty One Pilots','TwentyOnePilots.jpg','HipHop');
INSERT INTO PERFORMER (ID, NAME, IMAGEURI, GENRE) VALUES(6,'Lorde','Lorde.jpg','Pop');
INSERT INTO PERFORMER (ID, NAME, IMAGEURI, GENRE) VALUES(7,'Adele','Adele.jpg','RhythmAndBlues');
INSERT INTO PERFORMER (ID, NAME, IMAGEURI, GENRE) VALUES(8,'Lukas Graham','LukasGraham.jpg','Pop');
INSERT INTO PERFORMER (ID, NAME, IMAGEURI, GENRE) VALUES(9,'Stan Walker','StanWalker.jpg','RhythmAndBlues');
INSERT INTO PERFORMER (ID, NAME, IMAGEURI, GENRE) VALUES(10,'Pentatonix','Pentatonix.jpg','Acappella');
INSERT INTO PERFORMER (ID, NAME, IMAGEURI, GENRE) VALUES(11,'Ariana Grande','ArianaGrande.jpg','Pop');
INSERT INTO PERFORMER (ID, NAME, IMAGEURI, GENRE) VALUES(12,'BabyMetal','BaybMetal.jpg','Metal');
INSERT INTO PERFORMER (ID, NAME, IMAGEURI, GENRE) VALUES(13,'Train','Train.jpg','Rock');
INSERT INTO PERFORMER (ID, NAME, IMAGEURI, GENRE) VALUES(14,'Linkin Park','LinkinPark.jpg','Rock');
INSERT INTO PERFORMER (ID, NAME, IMAGEURI, GENRE) VALUES(15,'DJ Khaled','DjKhaled.jpg','HipHop');
INSERT INTO PERFORMER (ID, NAME, IMAGEURI, GENRE) VALUES(16,'Katy Perry','KatyPerry.jpg','Pop');
INSERT INTO PERFORMER (ID, NAME, IMAGEURI, GENRE) VALUES(17,'Metallica','Metallica.jpg','Metal');
INSERT INTO PERFORMER (ID, NAME, IMAGEURI, GENRE) VALUES(18,'Imagine Dragons','ImagineDragons.jpg','Rock');
INSERT INTO PERFORMER (ID, NAME, IMAGEURI, GENRE) VALUES(19,'John Legend','JohnLegend.jpg','RhythmAndBlues');
INSERT INTO PERFORMER (ID, NAME, IMAGEURI, GENRE) VALUES(20,'Zayn Malik','ZaynMalik.jpg','RhythmAndBlues');

INSERT INTO CONCERT (ID, TITLE, DATE, PERFORMER_ID) VALUES(1,'Death of a Bachelor Tour','2017-02-24 17:00:00',1);
INSERT INTO CONCERT (ID, TITLE, DATE, PERFORMER_ID) VALUES(2,'Divide Tour','2017-08-12 19:30:00',2);
INSERT INTO CONCERT (ID, TITLE, DATE, PERFORMER_ID) VALUES(3,'The Damn Tour','2017-07-27 16:45:00',3);
INSERT INTO CONCERT (ID, TITLE, DATE, PERFORMER_ID) VALUES(4,'24K Magic World Tour','2017-09-02 19:30:00',4);
INSERT INTO CONCERT (ID, TITLE, DATE, PERFORMER_ID) VALUES(5,'Emotional Roadshow World Tour','2017-04-01 13:15:00',5);
INSERT INTO CONCERT (ID, TITLE, DATE, PERFORMER_ID) VALUES(6,'Melodrama World Tour','2017-09-26 18:30:00',6);
INSERT INTO CONCERT (ID, TITLE, DATE, PERFORMER_ID) VALUES(7,'Adele Live 2017','2017-03-23 19:30:00',7);
INSERT INTO CONCERT (ID, TITLE, DATE, PERFORMER_ID) VALUES(8,'Lukas Graham','2017-07-30 14:30:00',8);
INSERT INTO CONCERT (ID, TITLE, DATE, PERFORMER_ID) VALUES(9,'Stan Walker','2017-08-18 19:45:00',9);
INSERT INTO CONCERT (ID, TITLE, DATE, PERFORMER_ID) VALUES(10,'Pentatonix World Tour 2017','2017-08-12 20:15:00',10);
INSERT INTO CONCERT (ID, TITLE, DATE, PERFORMER_ID) VALUES(11,'Dangerous Woman','2017-08-10 18:30:00',11);
INSERT INTO CONCERT (ID, TITLE, DATE, PERFORMER_ID) VALUES(12,'Legend - Metal Resistance','2017-09-19 18:15:00',12);
INSERT INTO CONCERT (ID, TITLE, DATE, PERFORMER_ID) VALUES(13,'Play That Song Tour','2017-05-30 17:30:00',13);
INSERT INTO CONCERT (ID, TITLE, DATE, PERFORMER_ID) VALUES(14,'One More Light Tour','2017-09-02 19:15:00',14);
INSERT INTO CONCERT (ID, TITLE, DATE, PERFORMER_ID) VALUES(15,'DJ Khaled','2017-07-29 21:30:00',15);
INSERT INTO CONCERT (ID, TITLE, DATE, PERFORMER_ID) VALUES(16,'Witness: The Tour','2017-09-07 18:30:00',16);
INSERT INTO CONCERT (ID, TITLE, DATE, PERFORMER_ID) VALUES(17,'WorldWired Tour','2017-08-14 19:45:00',17);
INSERT INTO CONCERT (ID, TITLE, DATE, PERFORMER_ID) VALUES(18,'Evolve!','2017-09-26 18:45:00',18);
INSERT INTO CONCERT (ID, TITLE, DATE, PERFORMER_ID) VALUES(19,'Darkness and Light World Tour','2017-06-27 17:45:00',19);
INSERT INTO CONCERT (ID, TITLE, DATE, PERFORMER_ID) VALUES(20,'One Love Manchester','2017-06-04 13:00:00',16);
INSERT INTO CONCERT (ID, TITLE, DATE, PERFORMER_ID) VALUES(21,'The Five Fox Festival','2017-08-29 20:30:00',17);
INSERT INTO CONCERT (ID, TITLE, DATE, PERFORMER_ID) VALUES(22,'Mind of Mine','2017-03-24 21:00:00',20);
